---
# tasks file for default_packages

- name: Установка программ #Имя задачи 
  apt: #Используемый модуль
    name: "{{ item }}" #Имя пакета из цикла
    state: present #Параметр действия. present - установить, absent - удалить
    update_cache: true
  become: true
  loop:
    - "{{ packages_to_install }}" #Цикл будет перебирать все значения из переменной "packages"
  when: ansible_distribution == "Debian" # Выполнится только на Debian системах