---
linux: #Группа хостов
  children: #Обозначение, что будет подгруппа хостов
    nginx: #Имя подгруппы хостов
      hosts: #Узлы группы
        vm_1: #Имя машины
          ansible_host: 89.169.147.251 #Адрес машины
        vm_2: #Имя машины
          ansible_host: 51.250.95.6 #Адрес машины
        vm_3: #Имя машины
          ansible_host: 89.169.150.221 #Адрес машины
  vars: #Переменные, доступные или используемые для всех подгрупп
    ansible_user: "test"
    ansible_ssh_private_key_file: "/home/test/.ssh/id_ed25519"
    connection_protocol: ssh #тип подключения
    ansible_become: false #Становиться ли другим пользователем после подключения