---
# tasks file for nginx_custom

- name: Установка Nginx 
  apt:
    name: "nginx"
    state: present
  become: true

- name: Ensure Nginx is installed
  apt:
    name: nginx
    state: present
    update_cache: yes

- name: Create Nginx proxy configuration
  copy:
    dest: /etc/nginx/sites-available/proxy.conf
    content: |
      server {
          listen 3000;
          server_name localhost;

          location / {
              proxy_pass http://{{ backend_server_ip }}:80;
              proxy_set_header Host $host;
              proxy_set_header X-Real-IP $remote_addr;
              proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
              proxy_set_header X-Forwarded-Proto $scheme;
          }
      }
  when: "'vm_2' in inventory_hostname" # Выполнится только тогда, когда в имени есть vm_2

- name: Enable the proxy configuration
  file:
    src: /etc/nginx/sites-available/proxy.conf
    dest: /etc/nginx/sites-enabled/proxy.conf
    state: link
  when: "'vm_2' in inventory_hostname" # Выполнится только тогда, когда в имени есть vm_2

- name: Remove default Nginx configuration
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  when: "'vm_2' in inventory_hostname" # Выполнится только тогда, когда в имени есть vm_2

- name: Подмена веб-страницы
  ansible.builtin.template:
    src: index.j2
    dest: /var/www/html/index.nginx-debian.html
  become: true
  notify: "Nginx Reloader"
